version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery

  celery:
    build: .
    command: celery -A app.celery_app worker --loglevel=info -Q celery,weather_queue
    volumes:
      - .:/app
    depends_on:
      - redis
